name: Setup Environment
description: Setup JDK and Gradle

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-write-only: ${{ inputs.update-cache }}
        cache-read-only: ${{ github.ref != 'refs/heads/1.20.1' }}
        add-job-summary: on-failure

    - name: Grant Execute Permission for gradlew
      shell: bash
      run: chmod +x gradlew